import Body from '@/components/body';
import './globals.css';
import type { Metadata } from 'next';
import { languages } from '../i18n/settings';
import { LayoutProps } from '@/types/document.type';

/**
 * ANCHOR Metadata
 * @date 19/04/2025 - 21:05:01
 *
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: 'SWD Frontend Test',
  description: 'Generated by create next app',
};

/**
 * ANCHOR Generate Static Params
 * @date 19/04/2025 - 21:05:40
 *
 * @export
 * @async
 * @returns {unknown}
 */
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

/**
 * ANCHOR Layout
 * @date 19/04/2025 - 21:08:37
 *
 * @async
 * @param {LayoutProps} props
 * @returns {unknown}
 */
const Layout = async (props: LayoutProps) => {
  const { children, params } = props;
  const { lng } = await params;

  // ANCHOR Render
  return (
    <html lang={lng}>
      <Body>{children}</Body>
    </html>
  );
};

export default Layout;
