import localFont from 'next/font/local';
import './globals.css';
import type { Metadata } from 'next';
import { languages } from '../i18n/settings';
import { LayoutProps } from '@/types/document.type';

/**
 * ANCHOR Geist Sans
 * @date 19/04/2025 - 21:05:19
 *
 * @type {*}
 */
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

/**
 * ANCHOR Geist Mono
 * @date 19/04/2025 - 21:05:06
 *
 * @type {*}
 */
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

/**
 * ANCHOR Metadata
 * @date 19/04/2025 - 21:05:01
 *
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * ANCHOR Generate Static Params
 * @date 19/04/2025 - 21:05:40
 *
 * @export
 * @async
 * @returns {unknown}
 */
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

/**
 * ANCHOR Layout
 * @date 19/04/2025 - 21:08:37
 *
 * @async
 * @param {LayoutProps} props
 * @returns {unknown}
 */
const Layout = async (props: LayoutProps) => {
  const { children, params } = props;
  const { locale } = await params;

  // ANCHOR Render
  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
};

export default Layout;
